### ISSUE TITLE
401 when trying to import

### ISSUE THREAD

**Issue by lnu** [onlyutkarsh/ExportImportBuildDefinition#16]
Whenever I try to import a definition it fails:
![image](https://cloud.githubusercontent.com/assets/1829553/23707318/36b63336-0412-11e7-8917-4979c9cb90fd.png)

![image](https://cloud.githubusercontent.com/assets/1829553/23707351/4adfb3be-0412-11e7-9128-40b3a89adab9.png)

We're using the latest version of the extension 0.0.8

It fails with a 401 when checking the queues

**Comment by onlyutkarsh** [comment]
@lnu Hey Laurent, Are you on TFS 2017? If not, you need to use [v0.0.2](https://github.com/onlyutkarsh/ExportImportBuildDefinition/releases/tag/v0.0.2) as the new scopes are not available in versions below TFS 2017.

**Comment by lnu** [comment]
You're right.

thank you

**Comment by onlyutkarsh** [comment]
Cool. Thanks!

**Comment by lnu** [comment]
Sorry but in the end, What should I do?
I'm using tfs 2017 with the latest version so it should work?

**Comment by onlyutkarsh** [comment]
Ah okay, yes, in that case, it should work. Can you try using a different browser? If that does not work, can you let me know...

- If you are importing the definition from different account/collection?
- Do you belong to [Build Administrators](https://www.visualstudio.com/en-us/docs/setup-admin/permissions#build-admin) group? Maybe you do not have access to read the queue?

As a workaround, try removing the `queue` section (like below) from exported JSON and see if imports successfully. 

```json
"queue": {
	"pool": {
	"id": 1,
	"name": "Default"
	},
	"id": 10,
	"name": "MyQueue"
}
```
Also, Is it possible to share the export json, so that I can try to find the root cause?

**Comment by lnu** [comment]
I already tried to remove the queue section, but even if there's no queue section a check is done:
``` // check pool with name and if yes, replace as it might have a different id
    let queues = await taskAgentRestClient.getAgentQueues(webContext.project.id);
    console.log("Got queues...");
    if (definition.queue && definition.queue.id && definition.queue.name) {

I'm also a member of the Build Administrators group

The definition I try to import comes from the same collection.

**Comment by onlyutkarsh** [comment]
Yeah looks like a bug to me. I took a quick look at the code and I think, I need to move that `queues` assignment in above snippet to the inside of the if block. I am currently traveling so fix might take some time. Can you try 0.0.2 version till that time? You might need to remove queue element from JSON still as 0.0.2 did not have the logic to assign the first available queue. Also, can you share the JSON (after removing the sensitive data), so that I can try it on your definition?

**Comment by onlyutkarsh** [comment]
Did not intend to close :-(

**Comment by lnu** [comment]
I tried to update the manifest with this:
```    "scopes": [
        "vso.build_execute",
        "vso.build",
        "vso.serviceendpoint",
        "vso.serviceendpoint_manage",
        "vso.agentpools",
        "vso.agentpools_manage"
    ],
```
But it stills the same. The strange thing is it's giving a 401 but if i take the link in chrome I get the results.

**Comment by onlyutkarsh** [comment]
I think it is working in browser URL because the request is using your credentials. It fails in the extension because the defined scopes in the extension are somehow not working for you. I will try to follow this up with the product group and see if I can find the answer. Meanwhile, I would suggest trying 0.0.2 version from releases

**Comment by lnu** [comment]
Version 15.105.25910.0

**Comment by onlyutkarsh** [comment]
@lnu thanks and sorry for responding late. The version tells me that you are on TFS 2017 RTM version and the scope `vso.agentpools` is available from TFS Update 1 RC2 onwards. However, TFS 2017 Update 1 is now [available](https://blogs.msdn.microsoft.com/bharry/2017/03/08/team-foundation-server-2017-update-1-available/) and applying that to your version should fix the above issue.

**Comment by lnu** [comment]
@onlyutkarsh Thanks! I did not notice it was available only in update1.
