### ISSUE TITLE
Build in new team project stalling

### ISSUE THREAD

**Issue by soccerjoshj07** [onlyutkarsh/ExportImportBuildDefinition#6]
### Installed product versions

0.0.2
### Description

Importing build to new project; seems to stall out on getting sources phase. We have updated the mappings to the files in the new project, but nothing is get therefore the build fails. If we change the scope from team project to project collection, it then works.

**Comment by onlyutkarsh** [comment]
@soccerjoshj07 the extension does not interact with source control, so I really doubt that it is the extension which is causing the issue. Since you mentioned you have already verified the mapping, can you check if you have any secure build variables in the definition as they do not get copied automatically? If your definition has secure variables, you might want to re-enter the values for secure variables.
